version: '3.8'

services:
  betguardian-api:
    build: .
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - sqlite-db

  sqlite-db:
    image: alpine:latest
    volumes:
      - ./data:/data
    command: sh -c "mkdir -p /data && touch /data/BetGuardian.db"
